[csi]
interface = ra0
bandwidth = 80

[udp]
enabled = true
host    = 192.168.8.100
port    = 5500

[mqtt]
enabled     = false
broker      = 127.0.0.1
port        = 1883
topic_raw   = csi/raw
topic_event = csi/event

[rest]
enabled = true
port    = 8080

[ubus]
enabled = true
object  = csi

[zones]
zone_0 = Living Room
zone_1 = Bedroom
zone_2 = Kitchen
